"""MCPP (neighborhood), sector, and citywide baseline geography helpers.

MCPP polygons/areas are vendored assets generated by ``scripts/generate_mcpp_areas.py``
(mirroring the beat assets). Sectors and the citywide region are derived from the beat
area CSV: SPD beats nest inside lettered sectors (beat ``C2`` ⊂ sector ``C``), and the
beats tile the city, so no additional geometry is needed for either.
"""
from __future__ import annotations

import csv
import json
import re
from math import isfinite
from pathlib import Path

from app.analysis.beat_baselines import BeatPolygons

DEFAULT_MCPP_AREA_CSV = (
    Path(__file__).resolve().parent.parent / "data" / "seattle_mcpp_areas_area.csv"
)
DEFAULT_MCPP_GEOJSON = (
    Path(__file__).resolve().parent.parent / "data" / "seattle_mcpp_areas.geojson"
)

# Placeholder values SPD records in the `mcpp` column that are not real neighborhoods:
# untagged/unknown rows and out-of-jurisdiction incidents. (NULL appears as a literal
# string in some SODA exports.)
NON_GEOGRAPHIC_MCPP: frozenset[str] = frozenset({"", "-", "UNKNOWN", "OOJ", "NULL"})

# A real SPD beat is one sector letter + digits (M3, B1). The harbor placeholder "99"
# and the non-geographic markers have no sector.
_SECTOR_RE = re.compile(r"^([A-Z])\d+$")


def normalize_mcpp(value: str | None) -> str | None:
    """Uppercased/stripped MCPP name, or ``None`` for the non-geographic placeholders."""
    if value is None:
        return None
    name = value.strip().upper()
    return None if name in NON_GEOGRAPHIC_MCPP else name


def sector_for_beat(beat: str | None) -> str | None:
    if not beat:
        return None
    match = _SECTOR_RE.match(beat.strip().upper())
    return match.group(1) if match else None


# Tokens .title() would mangle in user-facing labels: district acronyms and the
# compass suffixes SPD uses in MCPP names.
_LABEL_UPPER_TOKENS = frozenset({"SODO", "SLU", "NE", "NW", "SE", "SW"})


def mcpp_display_label(name: str) -> str:
    """Human display label for an UPPERCASE MCPP name ("SLU/CASCADE" → "SLU/Cascade")."""

    def fix(token: str) -> str:
        return token if token in _LABEL_UPPER_TOKENS else token.title()

    return "/".join(
        " ".join(fix(word) for word in part.split(" ")) for part in name.split("/")
    )


def load_mcpp_areas(path: Path | None = None) -> dict[str, float]:
    source = path or DEFAULT_MCPP_AREA_CSV
    areas: dict[str, float] = {}
    with Path(source).open(newline="", encoding="utf-8-sig") as handle:
        for row in csv.DictReader(handle):
            name = normalize_mcpp(row.get("mcpp"))
            if not name:
                continue
            area = float(row["area_km2"])
            if not isfinite(area) or area <= 0:
                raise ValueError(f"MCPP {name} has non-positive area {area}.")
            areas[name] = area
    return areas


def load_mcpp_polygons(path: Path | None = None) -> BeatPolygons:
    """WGS84 MCPP polygons in the ``BeatPolygons`` shape (name → polygons), so the
    generic point-in-polygon/overlap helpers in ``beat_baselines`` work unchanged."""
    source = path or DEFAULT_MCPP_GEOJSON
    with Path(source).open(encoding="utf-8") as handle:
        data = json.load(handle)

    polygons: BeatPolygons = {}
    for feature in data.get("features", []):
        name = normalize_mcpp(feature.get("properties", {}).get("mcpp"))
        geometry = feature.get("geometry") or {}
        geom_type = geometry.get("type")
        if not name:
            continue
        if geom_type == "Polygon":
            multi = [geometry["coordinates"]]
        elif geom_type == "MultiPolygon":
            multi = geometry["coordinates"]
        else:
            continue
        rings = [
            [[(float(x), float(y)) for x, y in ring] for ring in poly] for poly in multi
        ]
        polygons.setdefault(name, []).extend(rings)
    return polygons
